<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>Groundwork.MongoDb.TestingAdapter</PackageId>
    <Description>Groundwork.Testing adapter for the native MongoDB provider.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Groundwork.MongoDb/Groundwork.MongoDb.csproj" />
    <ProjectReference Include="../Groundwork.Testing/Groundwork.Testing.csproj" />
  </ItemGroup>

</Project>
