<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/valence-works/groundwork-v2</PackageProjectUrl>
    <RepositoryUrl>https://github.com/valence-works/groundwork-v2.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Authors>Valence Works</Authors>
    <Company>Valence Works</Company>
    <Copyright>Copyright © 2026 Valence Works</Copyright>
  </PropertyGroup>
</Project>
