<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Groundwork.Kernel/Groundwork.Kernel.csproj" />
    <ProjectReference Include="../../src/Groundwork.Substrate.Relational/Groundwork.Substrate.Relational.csproj" />
  </ItemGroup>

</Project>
