<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <IsRoslynComponent>true</IsRoslynComponent>
    <NoWarn>$(NoWarn);RS1042;RS1036;RS1032;RS2008</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <ProjectReference Include="../Groundwork.Schema/Groundwork.Schema.csproj" />
  </ItemGroup>

</Project>
