using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Groundwork.Schema;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Groundwork.Schema.Generator;

[Generator]
public sealed class SchemaGenerator : ISourceGenerator
{
    private static readonly DiagnosticDescriptor MissingKey = new(
        "GW_SCHEMA_TABLE_001",
        "A generated table requires a key",
        "Table '{0}' has no member marked [GwKey].",
        "Groundwork.Schema", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedType = new(
        "GW_SCHEMA_COLUMN_001",
        "Column type is not portable",
        "Column '{0}' has unsupported type '{1}'.",
        "Groundwork.Schema", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateColumn = new(
        "GW_SCHEMA_COLUMN_002",
        "Column name is duplicated",
        "Table '{0}' declares multiple members as column '{1}'.",
        "Groundwork.Schema", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateTable = new(
        "GW_SCHEMA_TABLE_002",
        "Table name is duplicated",
        "Schema table name '{0}' is declared more than once.",
        "Groundwork.Schema", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidDefault = new(
        "GW_SCHEMA_COLUMN_003",
        "Column default is not readable",
        "Column '{0}' declares a default that is not a valid {1}: {2}",
        "Groundwork.Schema", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidTablePolicy = new(
        "GW_SCHEMA_TABLE_003",
        "Table lifecycle policy is invalid",
        "Table '{0}' declares an invalid lifecycle policy: {1}",
        "Groundwork.Schema", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidIndex = new(
        "GW_SCHEMA_INDEX_001",
        "Index specification is invalid",
        "Index '{0}' has invalid specification: {1}",
        "Groundwork.Schema", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidSchemaFile = new(
        "GW_SCHEMA_JSON_001",
        "Schema AdditionalFile is invalid",
        "The Groundwork schema file '{0}' is invalid: {1}",
        "Groundwork.Schema", DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var tables = new List<GeneratedTable>();
        var emitGeneratedRows = context.Compilation.GetTypeByMetadataName("Groundwork.Query.Linq.GwGeneratedRows") is not null;
        var projections = emitGeneratedRows ? FindGeneratedProjections(context) : Array.Empty<GeneratedProjection>();
        if (emitGeneratedRows && context.Compilation.GetTypeByMetadataName("System.Runtime.CompilerServices.ModuleInitializerAttribute") is null)
        {
            context.AddSource("GroundworkModuleInitializer.g.cs", """
                // <auto-generated />
                namespace System.Runtime.CompilerServices
                {
                    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
                    internal sealed class ModuleInitializerAttribute : global::System.Attribute { }
                }
                """);
        }
        var hasTableDeclaration = false;
        var tableNames = new HashSet<string>(StringComparer.Ordinal);
        var seenTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var tree in context.Compilation.SyntaxTrees)
        {
            var root = tree.GetRoot(context.CancellationToken);
            var semanticModel = context.Compilation.GetSemanticModel(tree);
            foreach (var declaration in root.DescendantNodes().OfType<TypeDeclarationSyntax>())
            {
                if (semanticModel.GetDeclaredSymbol(declaration, context.CancellationToken) is not INamedTypeSymbol symbol ||
                    FindAttribute(symbol, "GwTableAttribute") is not { } tableAttribute)
                    continue;
                hasTableDeclaration = true;
                if (!seenTypes.Add(symbol))
                    continue;

                var table = BuildTable(context, symbol, tableAttribute);
                if (table is null)
                    continue;

                if (!tableNames.Add(table.Name))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DuplicateTable,
                        tableAttribute.ApplicationSyntaxReference?.GetSyntax(context.CancellationToken).GetLocation() ?? declaration.GetLocation(),
                        table.Name));
                    continue;
                }

                tables.Add(new GeneratedTable(
                    table,
                    symbol.Name,
                    symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString(),
                    symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    BuildGeneratedRow(symbol)));
            }
        }

        if (!hasTableDeclaration)
        {
            var schemaFile = ReadAdditionalSchema(context);
            if (schemaFile is not null)
            {
                tables.AddRange(schemaFile.Tables.Select(table => new GeneratedTable(table, Identifier(table.Name), null, null, null)));
                EmitStorageUnits(context, tables, emitGeneratedRows);
                EmitProjectionRegistrations(context, projections);
                EmitSchemaAttribute(context, schemaFile);
            }
            return;
        }

        var schema = new SchemaDocument(tables.Select(item => item.Table));
        EmitStorageUnits(context, tables, emitGeneratedRows);
        EmitProjectionRegistrations(context, projections);
        EmitSchemaAttribute(context, schema);
    }

    private static void EmitStorageUnits(
        GeneratorExecutionContext context,
        IReadOnlyList<GeneratedTable> tables,
        bool emitGeneratedRows)
    {
        for (var index = 0; index < tables.Count; index++)
        {
            var item = tables[index];
            var qualifiedName = string.IsNullOrWhiteSpace(item.NamespaceName)
                ? item.TypeName
                : $"{item.NamespaceName}_{item.TypeName}";
            context.AddSource(
                $"{Identifier(qualifiedName)}_{index}.g.cs",
                RenderStorageUnit(item, emitGeneratedRows));
        }
    }

    private static SchemaTable? BuildTable(
        GeneratorExecutionContext context,
        INamedTypeSymbol symbol,
        AttributeData tableAttribute)
    {
        var tableName = StringArgument(tableAttribute, 0) ?? symbol.Name;
        if (IsEmpty(context, tableAttribute, symbol.Name, "the table name", tableName))
            return null;
        var columns = new List<SchemaColumn>();
        var keys = new List<string>();
        var columnSymbols = new Dictionary<string, ISymbol>(StringComparer.Ordinal);

        foreach (var declared in DeclaredColumns(symbol))
        {
            var memberSymbol = declared.Symbol;
            var memberType = declared.Type;
            var columnAttribute = declared.Attribute;
            if (!TryMapType(memberType, out var type))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedType,
                    AttributeLocation(columnAttribute, context),
                    memberSymbol.Name,
                    memberType.ToDisplayString()));
                continue;
            }

            var name = StringNamedArgument(columnAttribute, "Name") ?? ToSnakeCase(memberSymbol.Name);
            if (IsEmpty(context, columnAttribute, tableName, $"the name of column '{memberSymbol.Name}'", name))
                continue;
            var nullable = IsNullable(memberType) && !BooleanNamedArgument(columnAttribute, "Required");
            SchemaDefault? columnDefault = null;
            if (StringNamedArgument(columnAttribute, "Default") is { } defaultText)
            {
                try
                {
                    columnDefault = GroundworkSchemaCanonical.ReadDefault(defaultText, type);
                }
                catch (Exception exception) when (exception is FormatException or OverflowException or System.Text.Json.JsonException)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        InvalidDefault,
                        AttributeLocation(columnAttribute, context),
                        name,
                        type.ToString(),
                        exception.Message));
                    continue;
                }
            }
            var column = new SchemaColumn(
                name,
                type,
                nullable,
                IntNamedArgument(columnAttribute, "Length"),
                IntNamedArgument(columnAttribute, "Precision"),
                IntNamedArgument(columnAttribute, "Scale"),
                EnumNamedArgument(columnAttribute, "Folding", TextFolding.None),
                EnumNamedArgument(columnAttribute, "Generation", SchemaGeneration.Supplied),
                columnDefault,
                StringNamedArgument(columnAttribute, "Id"));
            if (columnSymbols.ContainsKey(name))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DuplicateColumn,
                    AttributeLocation(columnAttribute, context),
                    tableName,
                    name));
                continue;
            }

            columns.Add(column);
            columnSymbols[name] = memberSymbol;
            if (FindAttribute(memberSymbol, "GwKeyAttribute") is not null)
                keys.Add(name);
        }

        if (keys.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                MissingKey,
                AttributeLocation(tableAttribute, context),
                tableName));
            return null;
        }

        var indexes = new List<SchemaIndex>();
        var indexNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var indexAttribute in symbol.GetAttributes().Where(attribute => IsAttribute(attribute, "GwIndexAttribute")))
        {
            var indexName = StringArgument(indexAttribute, 0) ?? "<unnamed>";
            if (IsEmpty(context, indexAttribute, tableName, "an index name", indexName))
                continue;
            if (!indexNames.Add(indexName))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidIndex,
                    IndexSpecificationLocation(indexAttribute, context.CancellationToken),
                    indexName,
                    "an index with this name is already declared on the table."));
                continue;
            }

            if (!TryParseIndex(context, indexAttribute, columnSymbols.Keys, out var index))
                continue;
            indexes.Add(new SchemaIndex(
                index.Name,
                index.Columns,
                BooleanNamedArgument(indexAttribute, "IncludeNulls", defaultValue: true),
                BooleanNamedArgument(indexAttribute, "Unique")));
        }

        var aggregations = new List<SchemaAggregation>();
        var aggregationNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var aggregateAttribute in symbol.GetAttributes().Where(attribute => IsAttribute(attribute, "GwAggregateAttribute")))
        {
            if (!TryParseAggregation(context, aggregateAttribute, tableName, out var aggregation))
                continue;
            if (!aggregationNames.Add(aggregation.Name))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidTablePolicy,
                    AttributeLocation(aggregateAttribute, context),
                    tableName,
                    $"aggregation '{aggregation.Name}' is declared more than once."));
                continue;
            }
            aggregations.Add(aggregation);
        }

        var token = StringNamedArgument(tableAttribute, "ConcurrencyToken");
        if (token is not null && IsEmpty(context, tableAttribute, tableName, "the concurrency token", token))
            return null;
        var interopView = StringNamedArgument(tableAttribute, "InteropView");
        if (interopView is not null && IsEmpty(context, tableAttribute, tableName, "the interop view", interopView))
            return null;

        return new SchemaTable(
            tableName,
            columns,
            keys,
            indexes,
            EnumNamedArgument(tableAttribute, "Scope", SchemaScope.Global),
            token is null ? null : new SchemaConcurrency(token),
            EnumNamedArgument(tableAttribute, "Timestamps", SchemaTimestamps.None),
            ReadRetention(context, symbol, tableName),
            ReadIdempotency(context, symbol, tableName, "GwAppendIdempotencyAttribute"),
            ReadIdempotency(context, symbol, tableName, "GwRetentionIdempotencyAttribute"),
            aggregations,
            StringNamedArgument(tableAttribute, "Id"),
            EnumNamedArgument(tableAttribute, "ForeignColumns", SchemaForeignColumns.Refuse),
            interopView: interopView);
    }

    private static SchemaRetention? ReadRetention(
        GeneratorExecutionContext context,
        INamedTypeSymbol symbol,
        string tableName)
    {
        if (FindAttribute(symbol, "GwRetentionAttribute") is not { } attribute)
            return null;
        var orderBy = StringArgument(attribute, 1);
        if (IsEmpty(context, attribute, tableName, "the retention order column", orderBy))
            return null;
        return new SchemaRetention(
            attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is int keepNewest ? keepNewest : 0,
            orderBy!,
            EnumNamedArgument(attribute, "Trigger", SchemaRetentionTrigger.Explicit),
            (StringNamedArgument(attribute, "PartitionBy") ?? string.Empty)
                .Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(column => column.Trim())
                .Where(column => column.Length != 0));
    }

    private static SchemaIdempotency? ReadIdempotency(
        GeneratorExecutionContext context,
        INamedTypeSymbol symbol,
        string tableName,
        string attributeName)
    {
        if (FindAttribute(symbol, attributeName) is not { } attribute)
            return null;
        var window = StringArgument(attribute, 0) ?? string.Empty;
        if (!TimeSpan.TryParse(window, CultureInfo.InvariantCulture, out var parsed))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                InvalidTablePolicy, AttributeLocation(attribute, context), tableName, $"'{window}' is not a time span."));
            return null;
        }
        var ledger = StringNamedArgument(attribute, "LedgerName");
        if (ledger is not null && IsEmpty(context, attribute, tableName, "the idempotency ledger name", ledger))
            return null;
        return new SchemaIdempotency(parsed, ledger);
    }

    private static bool TryParseAggregation(
        GeneratorExecutionContext context,
        AttributeData attribute,
        string tableName,
        out SchemaAggregation aggregation)
    {
        var name = StringArgument(attribute, 0) ?? "<unnamed>";
        if (IsEmpty(context, attribute, tableName, "an aggregation name", name))
        {
            aggregation = null!;
            return false;
        }
        var groupByColumns = new List<string>();
        var groupBy = new List<SchemaAggregationGroup>();
        var aggregates = new List<SchemaAggregate>();
        var location = AttributeLocation(attribute, context);
        foreach (var term in (StringArgument(attribute, 1) ?? string.Empty).Split(','))
        {
            var tokens = term.Trim().Split(new[] { ' ', '\t', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
            var parsed = tokens.Length != 0 && tokens[0] switch
            {
                "group" when tokens.Length == 2 => Add(groupByColumns, tokens[1]),
                "bucket" when tokens.Length == 4 && TimeSpan.TryParse(tokens[3], CultureInfo.InvariantCulture, out var width) =>
                    Add(groupBy, SchemaAggregationGroup.FixedUtcBucket(tokens[1], tokens[2], width)),
                "day" when tokens.Length == 3 => Add(groupBy, SchemaAggregationGroup.LocalCalendarDayBucket(tokens[1], tokens[2])),
                "count" when tokens.Length == 2 => Add(aggregates, SchemaAggregate.Count(tokens[1])),
                "min" when tokens.Length == 3 => Add(aggregates, SchemaAggregate.Min(tokens[1], tokens[2])),
                "max" when tokens.Length == 3 => Add(aggregates, SchemaAggregate.Max(tokens[1], tokens[2])),
                "sum" when tokens.Length == 3 => Add(aggregates, SchemaAggregate.Sum(tokens[1], tokens[2])),
                "setUnion" when tokens.Length == 4 && int.TryParse(tokens[3], NumberStyles.Integer, CultureInfo.InvariantCulture, out var maxValues) =>
                    Add(aggregates, SchemaAggregate.SetUnion(tokens[1], tokens[2], maxValues)),
                "firstBy" when tokens.Length == 5 && tokens[4] is "ASC" or "DESC" =>
                    Add(aggregates, SchemaAggregate.FirstBy(tokens[1], tokens[2], tokens[3], tokens[4] == "DESC")),
                _ => false
            };
            if (!parsed)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidTablePolicy, location, tableName,
                    $"aggregation '{name}' has an unreadable term '{term.Trim()}'."));
                aggregation = null!;
                return false;
            }
        }

        string? invalid = null;
        if (aggregates.Count == 0)
            invalid = $"aggregation '{name}' declares no aggregate.";
        else if (groupByColumns.Count != 0 && groupBy.Count != 0)
            invalid = $"aggregation '{name}' mixes plain 'group' terms with bucket grouping; use one or the other.";
        else if (groupByColumns.Count == 0 && groupBy.Count == 0)
            invalid = $"aggregation '{name}' declares no grouping term.";
        else if (groupBy.Count(group => group.Bucket != SchemaTimeBucket.None) > 1)
            invalid = $"aggregation '{name}' declares more than one time bucket.";
        if (invalid is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidTablePolicy, location, tableName, invalid));
            aggregation = null!;
            return false;
        }

        aggregation = new SchemaAggregation(name, aggregates, groupByColumns, groupBy);
        return true;
    }

    private static Location AttributeLocation(AttributeData attribute, GeneratorExecutionContext context) =>
        attribute.ApplicationSyntaxReference?.GetSyntax(context.CancellationToken).GetLocation() ?? Location.None;

    /// <summary>
    /// Refuses an empty attribute value as a build diagnostic. The schema model requires these to be
    /// non-empty, so without this the generator would fault instead of naming what is missing.
    /// </summary>
    private static bool IsEmpty(
        GeneratorExecutionContext context,
        AttributeData attribute,
        string tableName,
        string what,
        string? value)
    {
        if (!string.IsNullOrWhiteSpace(value))
            return false;
        context.ReportDiagnostic(Diagnostic.Create(
            InvalidTablePolicy, AttributeLocation(attribute, context), tableName, $"{what} cannot be empty."));
        return true;
    }

    private static bool Add<T>(List<T> target, T value)
    {
        target.Add(value);
        return true;
    }

    private static bool TryParseIndex(
        GeneratorExecutionContext context,
        AttributeData attribute,
        IEnumerable<string> declaredColumns,
        out SchemaIndex index)
    {
        var name = StringArgument(attribute, 0) ?? "<unnamed>";
        var specification = StringArgument(attribute, 1) ?? string.Empty;
        var known = new HashSet<string>(declaredColumns, StringComparer.Ordinal);
        var parsed = new List<SchemaIndexColumn>();
        var location = IndexSpecificationLocation(attribute, context.CancellationToken);

        foreach (var part in specification.Split(','))
        {
            var tokens = part.Trim().Split(new[] { ' ', '\t', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
            if (tokens.Length != 2 || (tokens[1] != "ASC" && tokens[1] != "DESC"))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidIndex, location, name,
                    $"expected '<column> ASC|DESC', got '{part.Trim()}'."));
                index = null!;
                return false;
            }

            if (!known.Contains(tokens[0]))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidIndex, location, name,
                    $"column '{tokens[0]}' is not declared on the table."));
                index = null!;
                return false;
            }

            if (parsed.Any(column => string.Equals(column.Name, tokens[0], StringComparison.Ordinal)))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidIndex, location, name,
                    $"column '{tokens[0]}' appears more than once."));
                index = null!;
                return false;
            }

            parsed.Add(new SchemaIndexColumn(tokens[0], tokens[1] == "DESC"));
        }

        if (parsed.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidIndex, location, name, "at least one column is required."));
            index = null!;
            return false;
        }

        index = new SchemaIndex(name, parsed);
        return true;
    }

    private static SchemaDocument? ReadAdditionalSchema(GeneratorExecutionContext context)
    {
        var configuredPath = GetOption(context, "gw_schema_file");
        var candidates = context.AdditionalFiles
            .Where(file => file.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
            .Where(file => configuredPath is null || PathsEqual(file.Path, configuredPath))
            .ToArray();
        if (configuredPath is null)
        {
            foreach (var file in candidates)
            {
                var filePath = GetFileOption(context, file, "gw_schema_file");
                if (!string.IsNullOrWhiteSpace(filePath))
                {
                    configuredPath = filePath;
                    break;
                }
            }
            if (configuredPath is not null)
                candidates = candidates.Where(file => PathsEqual(file.Path, configuredPath)).ToArray();
        }
        if (candidates.Length == 0)
            return null;
        var selected = candidates.First();
        var text = selected.GetText(context.CancellationToken)?.ToString();
        if (string.IsNullOrWhiteSpace(text))
            return null;
        try
        {
            return GroundworkSchemaCanonical.Parse(text!);
        }
        catch (Exception exception) when (exception is FormatException or InvalidOperationException or
                                          ArgumentException or System.Text.Json.JsonException)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidSchemaFile, Location.None, selected.Path, exception.Message));
            return null;
        }
    }

    private static string? GetOption(GeneratorExecutionContext context, string key)
    {
        if (context.AnalyzerConfigOptions.GlobalOptions.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value))
            return value;
        if (context.AnalyzerConfigOptions.GlobalOptions.TryGetValue($"build_property.{key}", out value) && !string.IsNullOrWhiteSpace(value))
            return value;
        return null;
    }

    private static string? GetFileOption(GeneratorExecutionContext context, AdditionalText file, string key)
    {
        if (context.AnalyzerConfigOptions.GetOptions(file).TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value))
            return value.Trim().Trim('"');
        return null;
    }

    private static void EmitSchemaAttribute(GeneratorExecutionContext context, SchemaDocument schema)
    {
        var canonical = GroundworkSchemaCanonical.Serialize(schema);
        var fingerprint = GroundworkSchemaCanonical.Fingerprint(schema);
        context.AddSource("GroundworkSchema.g.cs", $"// <auto-generated />\n[assembly: global::Groundwork.Schema.GroundworkSchemaAttribute({Literal(canonical)}, {Literal(fingerprint)})]\n");
    }

    private static IReadOnlyList<GeneratedProjection> FindGeneratedProjections(GeneratorExecutionContext context)
    {
        var candidates = new List<GeneratedProjection>();
        foreach (var tree in context.Compilation.SyntaxTrees)
        {
            var root = tree.GetRoot(context.CancellationToken);
            var semanticModel = context.Compilation.GetSemanticModel(tree);
            foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                if (semanticModel.GetSymbolInfo(invocation, context.CancellationToken).Symbol is not IMethodSymbol method ||
                    !IsGroundworkSelect(context.Compilation, method) ||
                    invocation.ArgumentList.Arguments.Count != 1 ||
                    invocation.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lambda ||
                    lambda.Body is not ExpressionSyntax body ||
                    method.ContainingType.TypeArguments.Length != 1 ||
                    method.TypeArguments.Length != 1 ||
                    method.ContainingType.TypeArguments[0] is not INamedTypeSymbol sourceType ||
                    method.TypeArguments[0] is not ITypeSymbol resultType ||
                    FindAttribute(sourceType, "GwTableAttribute") is null ||
                    !CanReferenceProjectionType(sourceType) ||
                    !CanReferenceProjectionType(resultType))
                    continue;

                var sourceParameter = lambda switch
                {
                    SimpleLambdaExpressionSyntax simple => semanticModel.GetDeclaredSymbol(simple.Parameter, context.CancellationToken),
                    ParenthesizedLambdaExpressionSyntax parenthesized when parenthesized.ParameterList.Parameters.Count == 1 =>
                        semanticModel.GetDeclaredSymbol(parenthesized.ParameterList.Parameters[0], context.CancellationToken),
                    _ => null
                };
                if (sourceParameter is not IParameterSymbol parameter)
                    continue;

                if (!TryBuildProjectionExpression(
                        body,
                        parameter,
                        semanticModel,
                        resultType,
                        context.CancellationToken,
                        out var projection))
                    continue;

                var factory = RenderProjectionFactory(projection, out var renderedColumnCount);
                if (renderedColumnCount == 0)
                    continue;

                candidates.Add(new GeneratedProjection(
                    TypeIdentity(resultType),
                    renderedColumnCount,
                    factory,
                    RenderProjectionResultType(resultType, projection)));
            }
        }

        var selected = new List<GeneratedProjection>();
        foreach (var group in candidates.GroupBy(candidate => (candidate.ResultTypeIdentity, candidate.ColumnCount)))
        {
            var shapes = group.GroupBy(candidate => candidate.Factory, StringComparer.Ordinal).ToArray();
            if (shapes.Length == 1)
                selected.Add(shapes[0].First());
        }
        return selected;
    }

    private static bool IsGroundworkSelect(Compilation compilation, IMethodSymbol method)
    {
        var containing = method.ContainingType.OriginalDefinition;
        return method.Name == "Select" &&
            method.TypeParameters.Length == 1 &&
            method.Parameters.Length == 1 &&
            (SymbolEqualityComparer.Default.Equals(
                containing,
                compilation.GetTypeByMetadataName("Groundwork.Query.Linq.IGwQueryable`1")) ||
             SymbolEqualityComparer.Default.Equals(
                containing,
                compilation.GetTypeByMetadataName("Groundwork.Query.Linq.GwQueryTable`1")));
    }

    private static bool TryBuildProjectionExpression(
        ExpressionSyntax syntax,
        IParameterSymbol sourceParameter,
        SemanticModel semanticModel,
        ITypeSymbol? expectedType,
        CancellationToken cancellationToken,
        out GeneratedProjectionExpression projection)
    {
        syntax = UnwrapProjectionSyntax(syntax);

        if (syntax is MemberAccessExpressionSyntax member &&
            IsProjectionMemberAccess(member, sourceParameter, semanticModel, cancellationToken) &&
            semanticModel.GetSymbolInfo(member, cancellationToken).Symbol is ISymbol memberSymbol &&
            TryProjectionColumn(memberSymbol))
        {
            var type = expectedType ?? semanticModel.GetTypeInfo(member, cancellationToken).Type;
            if (type is null || !CanUseProjectionReadType(type))
            {
                projection = null!;
                return false;
            }

            projection = new GeneratedProjectionRead(TypeName(type));
            return true;
        }

        if (syntax is AnonymousObjectCreationExpressionSyntax anonymous)
            return TryBuildAnonymousProjection(
                anonymous,
                sourceParameter,
                semanticModel,
                cancellationToken,
                out projection);

        if (syntax is ObjectCreationExpressionSyntax creation)
            return TryBuildNamedProjection(
                creation,
                creation.ArgumentList,
                creation.Initializer,
                semanticModel,
                sourceParameter,
                cancellationToken,
                out projection);

        if (syntax is ImplicitObjectCreationExpressionSyntax implicitCreation)
            return TryBuildNamedProjection(
                implicitCreation,
                implicitCreation.ArgumentList,
                implicitCreation.Initializer,
                semanticModel,
                sourceParameter,
                cancellationToken,
                out projection);

        projection = null!;
        return false;
    }

    private static bool TryBuildNamedProjection(
        SyntaxNode creation,
        ArgumentListSyntax? argumentList,
        InitializerExpressionSyntax? initializer,
        SemanticModel semanticModel,
        IParameterSymbol sourceParameter,
        CancellationToken cancellationToken,
        out GeneratedProjectionExpression projection)
    {
        var resultType = semanticModel.GetTypeInfo(creation, cancellationToken).Type as INamedTypeSymbol;
        var constructor = semanticModel.GetSymbolInfo(creation, cancellationToken).Symbol as IMethodSymbol;
        if (resultType is null || resultType.IsAnonymousType ||
            !CanReferenceProjectionType(resultType) ||
            constructor is null || constructor.MethodKind != MethodKind.Constructor ||
            !IsAccessibleFromGeneratedSource(constructor))
        {
            projection = null!;
            return false;
        }

        if ((argumentList?.Arguments.Count ?? 0) != constructor.Parameters.Length)
        {
            projection = null!;
            return false;
        }
        if (argumentList?.Arguments.Any(argument => argument.NameColon is not null) == true)
        {
            projection = null!;
            return false;
        }

        var constructorArguments = new List<GeneratedProjectionExpression>();
        for (var index = 0; index < (argumentList?.Arguments.Count ?? 0); index++)
        {
            if (!TryBuildProjectionExpression(
                    argumentList!.Arguments[index].Expression,
                    sourceParameter,
                    semanticModel,
                    constructor.Parameters[index].Type,
                    cancellationToken,
                    out var argument))
            {
                projection = null!;
                return false;
            }
            constructorArguments.Add(argument);
        }

        var assignments = new List<GeneratedProjectionAssignment>();
        if (initializer is not null)
        {
            foreach (var expression in initializer.Expressions)
            {
                if (expression is not AssignmentExpressionSyntax assignment ||
                    assignment.Kind() != SyntaxKind.SimpleAssignmentExpression ||
                    assignment.Left is not IdentifierNameSyntax identifier ||
                    semanticModel.GetSymbolInfo(assignment.Left, cancellationToken).Symbol is not ISymbol member ||
                    !TryProjectionAssignment(member, out var memberType))
                {
                    projection = null!;
                    return false;
                }

                if (!TryBuildProjectionExpression(
                        assignment.Right,
                        sourceParameter,
                        semanticModel,
                        memberType,
                        cancellationToken,
                        out var value))
                {
                    projection = null!;
                    return false;
                }
                assignments.Add(new GeneratedProjectionAssignment(identifier.Identifier.ValueText, TypeName(memberType), value));
            }
        }

        projection = new GeneratedProjectionObject(
            TypeName(resultType),
            constructorArguments,
            assignments,
            IsAnonymous: false);
        return true;
    }

    private static bool TryBuildAnonymousProjection(
        AnonymousObjectCreationExpressionSyntax anonymous,
        IParameterSymbol sourceParameter,
        SemanticModel semanticModel,
        CancellationToken cancellationToken,
        out GeneratedProjectionExpression projection)
    {
        if (semanticModel.GetTypeInfo(anonymous, cancellationToken).Type is not INamedTypeSymbol resultType ||
            !resultType.IsAnonymousType)
        {
            projection = null!;
            return false;
        }

        var assignments = new List<GeneratedProjectionAssignment>();
        foreach (var initializer in anonymous.Initializers)
        {
            var value = initializer.Expression;
            var memberName = initializer.NameEquals?.Name.Identifier.ValueText;
            if (memberName is null && semanticModel.GetSymbolInfo(value, cancellationToken).Symbol is ISymbol selected)
                memberName = selected.Name;
            if (memberName is null || resultType.GetMembers(memberName).SingleOrDefault() is not IPropertySymbol property)
            {
                projection = null!;
                return false;
            }

            if (!TryBuildProjectionExpression(
                    value,
                    sourceParameter,
                    semanticModel,
                    property.Type,
                    cancellationToken,
                    out var expression))
            {
                projection = null!;
                return false;
            }
            assignments.Add(new GeneratedProjectionAssignment(memberName, TypeName(property.Type), expression));
        }

        projection = new GeneratedProjectionObject(null, Array.Empty<GeneratedProjectionExpression>(), assignments, IsAnonymous: true);
        return true;
    }

    private static bool TryProjectionColumn(ISymbol member)
    {
        if (member is not IPropertySymbol and not IFieldSymbol ||
            member.IsStatic ||
            !IsAccessibleFromGeneratedSource(member) ||
            member.ContainingType is not INamedTypeSymbol declaringType ||
            !CanReferenceProjectionType(declaringType) ||
            member is IPropertySymbol { GetMethod: { } getter } && !IsAccessibleFromGeneratedSource(getter))
            return false;

        var memberType = member is IPropertySymbol property ? property.Type : ((IFieldSymbol)member).Type;
        if (FindAttribute(member, "GwColumnAttribute") is not { } attribute || !TryMapType(memberType, out _))
            return false;

        var columnName = StringNamedArgument(attribute, "Name") ?? ToSnakeCase(member.Name);
        return !string.IsNullOrWhiteSpace(columnName);
    }

    private static bool IsProjectionMemberAccess(
        MemberAccessExpressionSyntax member,
        IParameterSymbol sourceParameter,
        SemanticModel semanticModel,
        CancellationToken cancellationToken)
    {
        var receiver = UnwrapProjectionSyntax(member.Expression);
        if (semanticModel.GetSymbolInfo(receiver, cancellationToken).Symbol is IParameterSymbol directParameter)
            return SymbolEqualityComparer.Default.Equals(directParameter, sourceParameter);

        if (receiver is not MemberAccessExpressionSyntax navigation ||
            semanticModel.GetSymbolInfo(UnwrapProjectionSyntax(navigation.Expression), cancellationToken).Symbol is not IParameterSymbol navigationParameter)
            return false;
        return SymbolEqualityComparer.Default.Equals(navigationParameter, sourceParameter);
    }

    private static ExpressionSyntax UnwrapProjectionSyntax(ExpressionSyntax syntax)
    {
        while (true)
        {
            switch (syntax)
            {
                case ParenthesizedExpressionSyntax parenthesized:
                    syntax = parenthesized.Expression;
                    continue;
                case CastExpressionSyntax cast:
                    syntax = cast.Expression;
                    continue;
                case CheckedExpressionSyntax checkedExpression:
                    syntax = checkedExpression.Expression;
                    continue;
                case PostfixUnaryExpressionSyntax suppression when
                    suppression.Kind() == SyntaxKind.SuppressNullableWarningExpression:
                    syntax = suppression.Operand;
                    continue;
                default:
                    return syntax;
            }
        }
    }

    private static bool TryProjectionAssignment(ISymbol member, out ITypeSymbol memberType)
    {
        switch (member)
        {
            case IPropertySymbol property when !property.IsStatic &&
                property.SetMethod is { } setter && IsAccessibleFromGeneratedSource(setter):
                memberType = property.Type;
                return CanUseProjectionReadType(memberType);
            case IFieldSymbol field when !field.IsStatic && !field.IsReadOnly && IsAccessibleFromGeneratedSource(field):
                memberType = field.Type;
                return CanUseProjectionReadType(memberType);
            default:
                memberType = null!;
                return false;
        }
    }

    private static bool IsAccessibleFromGeneratedSource(ISymbol symbol) =>
        symbol.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal;

    private static bool CanReferenceProjectionType(ITypeSymbol type)
    {
        if (TryMapType(type, out _))
            return true;
        if (type is not INamedTypeSymbol named || named.Arity != 0 || named.IsRefLikeType)
            return false;
        if (named.IsAnonymousType)
            return true;
        for (var current = named; current is not null; current = current.ContainingType)
        {
            if (current.Arity != 0 || !IsAccessibleFromGeneratedSource(current))
                return false;
        }
        return true;
    }

    private static bool CanUseProjectionReadType(ITypeSymbol type) => TryMapType(type, out _);

    private static string TypeIdentity(ITypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string TypeName(ITypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string RenderProjectionFactory(GeneratedProjectionExpression projection, out int columnCount)
    {
        var ordinal = 0;
        var factory = RenderProjectionExpression(projection, ref ordinal);
        columnCount = ordinal;
        return factory;
    }

    private static string RenderProjectionExpression(GeneratedProjectionExpression projection, ref int ordinal)
    {
        switch (projection)
        {
            case GeneratedProjectionRead read:
                return "global::Groundwork.Query.Linq.GwGeneratedRowValue.ReadProjection<" + read.TypeName + ">(values, columns, " +
                    (ordinal++).ToString(CultureInfo.InvariantCulture) + ")";
            case GeneratedProjectionObject created when created.IsAnonymous:
                var anonymousAssignments = new List<string>();
                foreach (var assignment in created.Assignments)
                    anonymousAssignments.Add(EscapeIdentifier(assignment.Name) + " = " + RenderProjectionExpression(assignment.Value, ref ordinal));
                return "new { " + string.Join(", ", anonymousAssignments) + " }";
            case GeneratedProjectionObject created:
                var constructorArguments = new List<string>();
                foreach (var argument in created.ConstructorArguments)
                    constructorArguments.Add(RenderProjectionExpression(argument, ref ordinal));
                var result = "new " + created.TypeName + "(" + string.Join(", ", constructorArguments) + ")";
                if (created.Assignments.Count != 0)
                {
                    var assignments = new List<string>();
                    foreach (var assignment in created.Assignments)
                        assignments.Add(EscapeIdentifier(assignment.Name) + " = " + RenderProjectionExpression(assignment.Value, ref ordinal));
                    result += " { " + string.Join(", ", assignments) + " }";
                }
                return result;
            default:
                throw new InvalidOperationException("Unknown generated projection expression.");
        }
    }

    private static string RenderProjectionResultType(ITypeSymbol resultType, GeneratedProjectionExpression projection)
    {
        if (resultType is INamedTypeSymbol named && named.IsAnonymousType && projection is GeneratedProjectionObject anonymous)
        {
            return "new { " + string.Join(", ", anonymous.Assignments.Select(assignment =>
                EscapeIdentifier(assignment.Name) + " = default(" + assignment.TypeName + ")")) + " }.GetType()";
        }
        return "typeof(" + TypeName(resultType) + ")";
    }

    private static void EmitProjectionRegistrations(
        GeneratorExecutionContext context,
        IReadOnlyList<GeneratedProjection> projections)
    {
        if (projections.Count == 0)
            return;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("internal static class GroundworkGeneratedProjectionRegistrations");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("    internal static void Register()");
        builder.AppendLine("    {");
        foreach (var projection in projections)
        {
            builder.Append("        global::Groundwork.Query.Linq.GwGeneratedRows.RegisterProjection(")
                .Append(projection.ResultTypeExpression).Append(", ")
                .Append(projection.ColumnCount.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            builder.Append("            static (values, columns) => ").Append(projection.Factory).AppendLine(");");
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
        context.AddSource("GroundworkGeneratedProjections.g.cs", builder.ToString());
    }

    private static GeneratedRow? BuildGeneratedRow(INamedTypeSymbol symbol)
    {
        if (!CanReferenceGeneratedRow(symbol))
            return null;
        var declaredMembers = DeclaredColumns(symbol)
            .Where(member => member.Symbol.DeclaredAccessibility == Accessibility.Public)
            .Where(member => member.Symbol is not IPropertySymbol property ||
                property.GetMethod?.DeclaredAccessibility == Accessibility.Public)
            .ToArray();
        var members = declaredMembers
            .Select(member =>
            {
                var initializable = member.Symbol is IPropertySymbol
                {
                    SetMethod: { DeclaredAccessibility: Accessibility.Public } setter
                } property && (setter.IsInitOnly || property.IsRequired);
                var writable = member.Symbol switch
                {
                    IPropertySymbol writableProperty => writableProperty.SetMethod is
                        { DeclaredAccessibility: Accessibility.Public, IsInitOnly: false } && !writableProperty.IsRequired,
                    IFieldSymbol field => !field.IsReadOnly && field.DeclaredAccessibility == Accessibility.Public,
                    _ => false
                };
                return new GeneratedMember(
                    member.Symbol.Name,
                    StringNamedArgument(member.Attribute, "Name") ?? ToSnakeCase(member.Symbol.Name),
                    member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    writable,
                    initializable,
                    member.Symbol is IPropertySymbol { IsRequired: true });
            })
            .ToArray();
        if (members.Length == 0)
            return null;

        var constructor = symbol.InstanceConstructors
            .Where(candidate => candidate.DeclaredAccessibility == Accessibility.Public)
            .Select(candidate => new
            {
                Candidate = candidate,
                Bound = candidate.Parameters.Select(parameter => members.SingleOrDefault(member =>
                    string.Equals(member.Name, parameter.Name, StringComparison.OrdinalIgnoreCase) &&
                    SymbolEqualityComparer.Default.Equals(parameter.Type, symbol.GetMembers(member.Name)
                        .Select(item => item is IPropertySymbol property ? property.Type : (item as IFieldSymbol)?.Type)
                        .FirstOrDefault(type => type is not null)))).ToArray()
            })
            .Where(candidate => candidate.Bound.All(member => member is not null))
            .Where(candidate => members.All(member =>
                candidate.Bound.Contains(member) || member.Writable || member.Initializable))
            .OrderByDescending(candidate => candidate.Candidate.Parameters.Length)
            .FirstOrDefault();
        if (constructor is null && !symbol.IsValueType)
            return null;

        return new GeneratedRow(
            members,
            constructor?.Bound.Where(member => member is not null).Cast<GeneratedMember>().ToArray() ?? Array.Empty<GeneratedMember>(),
            constructor is not null && FindAttribute(constructor.Candidate, "SetsRequiredMembersAttribute") is not null);
    }

    private static IEnumerable<DeclaredColumn> DeclaredColumns(INamedTypeSymbol symbol)
    {
        foreach (var member in symbol.GetMembers())
        {
            var type = member switch
            {
                IPropertySymbol { IsStatic: false } property => property.Type,
                IFieldSymbol { IsStatic: false } field => field.Type,
                _ => null
            };
            if (type is not null && FindAttribute(member, "GwColumnAttribute") is { } attribute)
                yield return new DeclaredColumn(member, type, attribute);
        }
    }

    private static bool CanReferenceGeneratedRow(INamedTypeSymbol symbol)
    {
        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            if (current.Arity != 0 || current.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
                return false;
        }
        return true;
    }

    private static string RenderStorageUnit(GeneratedTable generated, bool emitGeneratedRows)
    {
        var table = generated.Table;
        var clrTypeName = generated.TypeName;
        var namespaceName = generated.NamespaceName;
        var typeName = Identifier(clrTypeName) + "StorageUnit";
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(namespaceName))
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
        builder.Append("public static class ").Append(typeName).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    public static global::Groundwork.Kernel.StorageUnit Definition { get; } = Build();");
        builder.AppendLine();
        builder.AppendLine("    private static global::Groundwork.Kernel.StorageUnit Build()");
        builder.AppendLine("    {");
        builder.Append("        var declaration = global::Groundwork.Kernel.StorageUnit.Declare(")
            .Append(Literal(table.LogicalId)).Append(", ").Append(Literal(table.Name)).AppendLine(")");
        foreach (var column in table.Columns)
        {
            builder.Append("            .Column(").Append(Literal(column.Name)).Append(", global::Groundwork.Kernel.PortableType.").Append(column.Type switch
            {
                SchemaValueType.String => "String",
                SchemaValueType.Int32 => "Int32",
                SchemaValueType.Int64 => "Int64",
                SchemaValueType.Decimal => "Decimal",
                SchemaValueType.Boolean => "Boolean",
                SchemaValueType.DateTimeOffset => "DateTimeOffset",
                SchemaValueType.Guid => "Guid",
                SchemaValueType.Binary => "Binary",
                _ => "Json"
            });
            var columnOptions = new List<string>();
            if (!column.IsNullable)
                columnOptions.Add("Required()");
            if (column.Length.HasValue)
                columnOptions.Add("MaxLength(" + column.Length.Value + ")");
            if (column.Precision.HasValue && column.Scale.HasValue)
                columnOptions.Add("Precision(" + column.Precision.Value + ", " + column.Scale.Value + ")");
            if (column.Folding != TextFolding.None)
                columnOptions.Add("Collation(global::Groundwork.Kernel.PortableCollation." +
                    (column.Folding == TextFolding.AsciiIgnoreCase ? "OrdinalIgnoreCase" : "UnicodeOrdinalIgnoreCase") + ")");
            if (column.Generation == SchemaGeneration.ProviderSequence)
                columnOptions.Add("ProviderSequence()");
            if (column.Default is { } columnDefault)
                columnOptions.Add("Default(" + DefaultLiteral(columnDefault.Value, column.Type) + ")");
            if (column.Id is { } columnId && columnId != column.Name)
                columnOptions.Add("LogicalId(" + Literal(columnId) + ")");
            if (columnOptions.Count > 0)
                builder.Append(", column => column.").Append(string.Join(".", columnOptions));
            builder.AppendLine(")");
        }
        builder.AppendLine("            .Key(");
        builder.AppendLine("                new string[]");
        builder.AppendLine("                {");
        foreach (var key in table.Key)
            builder.Append("                    ").Append(Literal(key)).AppendLine(",");
        builder.AppendLine("                })");
        foreach (var index in table.Indexes)
        {
            builder.Append("            .").Append(index.Unique ? "UniqueIndex" : "Index").Append("(").Append(Literal(index.Name)).AppendLine(", index => index");
            foreach (var column in index.Columns)
                builder.Append("                .").Append(column.Descending ? "Descending" : "Column").Append("(").Append(Literal(column.Name)).AppendLine(")");
            if (!index.IncludeNulls)
                builder.AppendLine("                .ExcludeMissingValues()");
            builder.AppendLine("            )");
        }
        foreach (var reference in table.References)
        {
            builder.Append("            .Reference(").Append(Literal(reference.Name))
                .Append(", new global::Groundwork.Kernel.StorageUnitId(").Append(Literal(reference.Target))
                .Append("), new string[] { ")
                .Append(string.Join(", ", reference.Columns.Select(Literal)))
                .AppendLine(" })");
        }
        if (table.Scope == SchemaScope.Scoped)
            builder.AppendLine("            .Scoped()");
        if (table.InteropView is { } interopView)
            builder.Append("            .InteropView(").Append(Literal(interopView)).AppendLine(")");
        if (table.ForeignColumns == SchemaForeignColumns.TolerateDatabaseSupplied)
            builder.AppendLine("            .TolerateForeignColumns()");
        if (table.Concurrency is { } concurrency)
            builder.Append("            .OptimisticConcurrency(").Append(Literal(concurrency.TokenColumn)).AppendLine(")");
        if (table.Retention is { } retention)
        {
            builder.Append("            .Retention(").Append(retention.KeepNewest.ToString(CultureInfo.InvariantCulture))
                .Append(", ").Append(Literal(retention.OrderBy))
                .Append(", global::Groundwork.Kernel.RetentionTrigger.").Append(retention.Trigger);
            foreach (var column in retention.PartitionBy)
                builder.Append(", ").Append(Literal(column));
            builder.AppendLine(")");
        }
        if (table.AppendIdempotency is { } append)
            builder.Append("            .AppendIdempotency(").Append(Window(append)).AppendLine(")");
        if (table.RetentionIdempotency is { } retentionIdempotency)
            builder.Append("            .RetentionIdempotency(").Append(Window(retentionIdempotency)).AppendLine(")");
        foreach (var aggregation in table.Aggregations)
        {
            builder.Append("            .Aggregate(").Append(Literal(aggregation.Name)).AppendLine(", aggregate => aggregate");
            if (aggregation.GroupByColumns.Count != 0)
            {
                builder.Append("                .GroupBy(")
                    .Append(string.Join(", ", aggregation.GroupByColumns.Select(Literal))).AppendLine(")");
            }
            foreach (var group in aggregation.GroupBy)
            {
                builder.Append("                ").AppendLine(group.Bucket switch
                {
                    SchemaTimeBucket.FixedUtc => $".FixedUtcBucket({Literal(group.Alias)}, {Literal(group.SourceColumn!)}, {Ticks(group.Width)})",
                    SchemaTimeBucket.LocalCalendarDay => $".LocalCalendarDayBucket({Literal(group.Alias)}, {Literal(group.SourceColumn!)})",
                    _ => $".GroupBy(new global::Groundwork.Kernel.AggregationGroup.Column({Literal(group.Alias)}))"
                });
            }
            foreach (var aggregate in aggregation.Aggregates)
            {
                builder.Append("                ").AppendLine(aggregate.Kind switch
                {
                    SchemaAggregateKind.Count => $".Count({Literal(aggregate.Alias)})",
                    SchemaAggregateKind.SetUnion => $".SetUnion({Literal(aggregate.Alias)}, {Literal(aggregate.Column!)}, {aggregate.MaxValues.ToString(CultureInfo.InvariantCulture)})",
                    SchemaAggregateKind.FirstBy => $".FirstBy({Literal(aggregate.Alias)}, {Literal(aggregate.Column!)}, {Literal(aggregate.OrderBy!)}, global::Groundwork.Kernel.SortDirection.{(aggregate.Descending ? "Descending" : "Ascending")})",
                    _ => $".{aggregate.Kind}({Literal(aggregate.Alias)}, {Literal(aggregate.Column!)})"
                });
            }
            builder.AppendLine("            )");
        }
        builder.AppendLine("        ;");
        builder.AppendLine("        return declaration.Build();");
        builder.AppendLine("    }");
        if (emitGeneratedRows && generated.ClrTypeName is not null && generated.Row is not null)
            RenderGeneratedRowRegistration(builder, generated.ClrTypeName, generated.Row);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void RenderGeneratedRowRegistration(StringBuilder builder, string clrTypeName, GeneratedRow row)
    {
        builder.AppendLine();
        builder.AppendLine("    internal static class GeneratedRowRegistration");
        builder.AppendLine("    {");
        builder.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void Register()");
        builder.AppendLine("        {");
        builder.Append("            global::Groundwork.Query.Linq.GwGeneratedRows.Register(new global::Groundwork.Query.Linq.GwGeneratedRowAccessor<")
            .Append(clrTypeName).AppendLine(">");
        builder.AppendLine("            (");
        builder.Append("                new global::Groundwork.Query.Linq.GwGeneratedRowMember<").Append(clrTypeName).AppendLine(">[]");
        builder.AppendLine("                {");
        foreach (var member in row.Members)
        {
            builder.Append("                    new(").Append(Literal(member.Name)).Append(", ")
                .Append(Literal(member.ColumnName)).Append(", typeof(").Append(member.TypeName)
                .Append("), static value => value.").Append(EscapeIdentifier(member.Name)).AppendLine("),");
        }
        builder.AppendLine("                },");
        builder.AppendLine("                static (values, columns, optionalColumns) =>");
        builder.AppendLine("                {");
        builder.Append("                    var value = new ").Append(clrTypeName).Append("(");
        builder.Append(string.Join(", ", row.ConstructorMembers.Select(member => GeneratedRead(member))));
        builder.Append(")");
        var initializers = row.Members.Where(member =>
            member.Initializable &&
            (!row.ConstructorMembers.Contains(member) || member.Required && !row.ConstructorSetsRequiredMembers)).ToArray();
        if (initializers.Length == 0)
        {
            builder.AppendLine(";");
        }
        else
        {
            builder.AppendLine();
            builder.AppendLine("                    {");
            foreach (var member in initializers)
            {
                builder.Append("                        ").Append(EscapeIdentifier(member.Name)).Append(" = ")
                    .Append(GeneratedRead(member)).AppendLine(",");
            }
            builder.AppendLine("                    };");
        }
        foreach (var member in row.Members.Where(member => member.Writable && !row.ConstructorMembers.Contains(member)))
        {
            builder.Append("                    if (columns.ContainsKey(").Append(Literal(member.Name)).AppendLine("))");
            builder.Append("                        value.").Append(EscapeIdentifier(member.Name)).Append(" = ")
                .Append(GeneratedRead(member)).AppendLine(";");
        }
        builder.AppendLine("                    return value;");
        builder.AppendLine("                }));");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static string GeneratedRead(GeneratedMember member) =>
        "global::Groundwork.Query.Linq.GwGeneratedRowValue.Read<" + member.TypeName + ">(" +
        "values, columns, optionalColumns, " + Literal(member.Name) + ", " + Literal(member.ColumnName) + ")";

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;

    private static string Window(SchemaIdempotency idempotency) =>
        Ticks(idempotency.Window) + (idempotency.LedgerName is null ? string.Empty : ", " + Literal(idempotency.LedgerName));

    private static string Ticks(TimeSpan value) =>
        "global::System.TimeSpan.FromTicks(" + value.Ticks.ToString(CultureInfo.InvariantCulture) + "L)";

    private static string DefaultLiteral(object? value, SchemaValueType type)
    {
        if (value is null)
            return "null";
        return type switch
        {
            SchemaValueType.String => Literal((string)value),
            SchemaValueType.Int32 => Convert.ToInt32(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture),
            SchemaValueType.Int64 => Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture) + "L",
            SchemaValueType.Decimal => Convert.ToDecimal(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture) + "m",
            SchemaValueType.Boolean => Convert.ToBoolean(value, CultureInfo.InvariantCulture) ? "true" : "false",
            SchemaValueType.DateTimeOffset =>
                $"new global::System.DateTimeOffset({((DateTimeOffset)value).UtcDateTime.Ticks.ToString(CultureInfo.InvariantCulture)}L, global::System.TimeSpan.Zero)",
            SchemaValueType.Guid => $"new global::System.Guid({Literal(((Guid)value).ToString("D", CultureInfo.InvariantCulture))})",
            SchemaValueType.Binary => $"global::System.Convert.FromBase64String({Literal(Convert.ToBase64String((byte[])value))})",
            _ => JsonLiteral(value)
        };
    }

    private static string JsonLiteral(object? value)
    {
        switch (value)
        {
            case null:
                return "null";
            case string text:
                return Literal(text);
            case bool boolean:
                return boolean ? "true" : "false";
            case int int32:
                return int32.ToString(CultureInfo.InvariantCulture);
            case long int64:
                return int64.ToString(CultureInfo.InvariantCulture) + "L";
            case decimal number:
                return number.ToString(CultureInfo.InvariantCulture) + "m";
            case IReadOnlyDictionary<string, object?> map:
                return "new global::System.Collections.Generic.Dictionary<string, object?>(global::System.StringComparer.Ordinal) { " +
                    string.Join(", ", map.Select(entry => $"[{Literal(entry.Key)}] = {JsonLiteral(entry.Value)}")) + " }";
            case IEnumerable sequence:
                return "new global::System.Collections.Generic.List<object?> { " +
                    string.Join(", ", sequence.Cast<object?>().Select(JsonLiteral)) + " }";
            default:
                throw new ArgumentOutOfRangeException(nameof(value));
        }
    }

    private static AttributeData? FindAttribute(ISymbol symbol, string name) =>
        symbol.GetAttributes().FirstOrDefault(attribute => IsAttribute(attribute, name));

    private static bool IsAttribute(AttributeData attribute, string name) =>
        string.Equals(attribute.AttributeClass?.Name, name, StringComparison.Ordinal) ||
        string.Equals(attribute.AttributeClass?.Name, name.Replace("Attribute", string.Empty), StringComparison.Ordinal);

    private static string? StringArgument(AttributeData attribute, int index) =>
        attribute.ConstructorArguments.Length > index
            ? attribute.ConstructorArguments[index].Value as string
            : AttributeSyntaxArgument(attribute, index)?.Token.ValueText;

    private static string? StringNamedArgument(AttributeData attribute, string name) =>
        NamedStringValue(attribute, name) ?? SyntaxStringValue(attribute, name);

    private static string? NamedStringValue(AttributeData attribute, string name) =>
        attribute.NamedArguments.FirstOrDefault(argument => argument.Key == name).Value.Value as string;

    private static string? SyntaxStringValue(AttributeData attribute, string name)
    {
        var expression = NamedSyntaxArgument(attribute, name)?.Expression;
        return expression is LiteralExpressionSyntax literal ? literal.Token.ValueText : null;
    }

    private static int? IntNamedArgument(AttributeData attribute, string name)
    {
        var value = attribute.NamedArguments.FirstOrDefault(argument => argument.Key == name).Value;
        if (value.Value is int number && number >= 0)
            return number;
        return int.TryParse(NamedSyntaxArgument(attribute, name)?.Expression.ToString(), out var syntaxNumber) && syntaxNumber >= 0
            ? syntaxNumber
            : null;
    }

    private static bool BooleanNamedArgument(AttributeData attribute, string name, bool defaultValue = false)
    {
        var value = attribute.NamedArguments.FirstOrDefault(argument => argument.Key == name).Value;
        if (value.Value is bool result)
            return result;
        return bool.TryParse(NamedSyntaxArgument(attribute, name)?.Expression.ToString(), out var syntaxResult)
            ? syntaxResult
            : defaultValue;
    }

    private static T EnumNamedArgument<T>(AttributeData attribute, string name, T defaultValue) where T : struct, Enum
    {
        var value = attribute.NamedArguments.FirstOrDefault(argument => argument.Key == name).Value;
        if (value.Value is int number && Enum.IsDefined(typeof(T), number))
            return (T)Enum.ToObject(typeof(T), number);
        var text = NamedSyntaxArgument(attribute, name)?.Expression.ToString();
        return Enum.TryParse<T>(text, ignoreCase: false, out var syntaxValue) ? syntaxValue : defaultValue;
    }

    private static bool IsNullable(ITypeSymbol type) =>
        type.IsReferenceType ? type.NullableAnnotation == NullableAnnotation.Annotated :
        type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

    private static bool TryMapType(ITypeSymbol type, out SchemaValueType mapped)
    {
        var underlying = type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T && type is INamedTypeSymbol nullable
            ? nullable.TypeArguments[0]
            : type;
        mapped = underlying.SpecialType switch
        {
            SpecialType.System_String => SchemaValueType.String,
            SpecialType.System_Int32 => SchemaValueType.Int32,
            SpecialType.System_Int64 => SchemaValueType.Int64,
            SpecialType.System_Decimal => SchemaValueType.Decimal,
            SpecialType.System_Boolean => SchemaValueType.Boolean,
            _ => default
        };
        if (mapped != default || underlying.SpecialType == SpecialType.System_String)
            return true;
        var display = underlying.ToDisplayString();
        if (display == "System.DateTimeOffset") { mapped = SchemaValueType.DateTimeOffset; return true; }
        if (display == "System.Guid") { mapped = SchemaValueType.Guid; return true; }
        if (display == "byte[]") { mapped = SchemaValueType.Binary; return true; }
        if (display == "object") { mapped = SchemaValueType.Json; return true; }
        return false;
    }

    private static Location IndexSpecificationLocation(AttributeData attribute, CancellationToken cancellationToken)
    {
        if (attribute.ApplicationSyntaxReference?.GetSyntax(cancellationToken) is AttributeSyntax syntax && syntax.ArgumentList?.Arguments.Count > 1)
            return syntax.ArgumentList.Arguments[1].GetLocation();
        return attribute.ApplicationSyntaxReference?.GetSyntax(cancellationToken).GetLocation() ?? Location.None;
    }

    private static LiteralExpressionSyntax? AttributeSyntaxArgument(AttributeData attribute, int index)
    {
        var syntax = attribute.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        return syntax?.ArgumentList?.Arguments.Count > index
            ? syntax.ArgumentList.Arguments[index].Expression as LiteralExpressionSyntax
            : null;
    }

    private static AttributeArgumentSyntax? NamedSyntaxArgument(AttributeData attribute, string name)
    {
        var syntax = attribute.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
        return syntax?.ArgumentList?.Arguments
            .FirstOrDefault(argument => argument.NameEquals?.Name.Identifier.ValueText == name);
    }

    private static string Identifier(string value)
    {
        var builder = new StringBuilder();
        foreach (var character in value)
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        if (builder.Length == 0 || char.IsDigit(builder[0])) builder.Insert(0, '_');
        return builder.ToString();
    }

    private static string ToSnakeCase(string value)
    {
        var builder = new StringBuilder();
        for (var index = 0; index < value.Length; index++)
        {
            var character = value[index];
            if (char.IsUpper(character) && index > 0) builder.Append('_');
            builder.Append(char.ToLowerInvariant(character));
        }
        return builder.ToString();
    }

    private static string Literal(string value) => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    private static bool PathsEqual(string left, string right)
    {
        var normalizedLeft = left.Replace('\\', '/');
        var normalizedRight = right.Trim().Trim('"').Replace('\\', '/').TrimStart('/');
        if (string.Equals(normalizedLeft.TrimStart('/'), normalizedRight, StringComparison.OrdinalIgnoreCase))
            return true;

        return !System.IO.Path.IsPathRooted(right) &&
            normalizedLeft.EndsWith('/' + normalizedRight, StringComparison.OrdinalIgnoreCase);
    }

    private sealed record GeneratedMember(
        string Name,
        string ColumnName,
        string TypeName,
        bool Writable,
        bool Initializable,
        bool Required);

    private sealed record GeneratedRow(
        IReadOnlyList<GeneratedMember> Members,
        IReadOnlyList<GeneratedMember> ConstructorMembers,
        bool ConstructorSetsRequiredMembers);

    private sealed record DeclaredColumn(ISymbol Symbol, ITypeSymbol Type, AttributeData Attribute);

    private abstract record GeneratedProjectionExpression;

    private sealed record GeneratedProjectionRead(string TypeName) : GeneratedProjectionExpression;

    private sealed record GeneratedProjectionAssignment(
        string Name,
        string TypeName,
        GeneratedProjectionExpression Value);

    private sealed record GeneratedProjectionObject(
        string? TypeName,
        IReadOnlyList<GeneratedProjectionExpression> ConstructorArguments,
        IReadOnlyList<GeneratedProjectionAssignment> Assignments,
        bool IsAnonymous) : GeneratedProjectionExpression;

    private sealed record GeneratedProjection(
        string ResultTypeIdentity,
        int ColumnCount,
        string Factory,
        string ResultTypeExpression);

    private sealed record GeneratedTable(
        SchemaTable Table,
        string TypeName,
        string? NamespaceName,
        string? ClrTypeName,
        GeneratedRow? Row);
}
